[variables]
NODE_VERSION = "18"

[phases.setup]
nixPkgs = ["nodejs_18", "python311", "ffmpeg"]
aptPkgs = ["python3-pip", "yt-dlp"]

[phases.install]
cmds = [
    "npm install"
]

[start]
cmd = "npm start"
