[variables]
NODE_VERSION = "18"
NPM_VERSION = "8"

[phases.setup]
nixPkgs = ["nodejs_18", "python311", "ffmpeg"]

[phases.install]
cmds = [
    "npm install",
    "python -m pip install --upgrade pip",
    "pip install yt-dlp"
]

[start]
cmd = "npm start"
